# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

includes:
    basic: ./basic/taskfile.yml
    with-azure-functions: ./with-azure-functions/taskfile.yml
    with-cache: ./with-cache/taskfile.yml
    with-cli: ./with-cli/taskfile.yml
    with-cobra: ./with-cobra/taskfile.yml
    with-custom-functions: ./with-custom-functions/taskfile.yml
    with-custom-type-mapping: ./with-custom-type-mapping/taskfile.yml
    with-gorm: ./with-gorm/taskfile.yml
    with-multi-content-types: ./with-multi-content-types/taskfile.yml
    with-swagger-ui: ./with-swagger-ui/taskfile.yml
    with-validation: ./with-validation/taskfile.yml

tasks:
    run:
        cmds:
        - for:
            - basic
            - with-azure-functions
            - with-cache
            - with-cli
            - with-cobra
            - with-custom-functions
            - with-custom-type-mapping
            - with-gorm
            - with-multi-content-types
            - with-swagger-ui
            - with-validation
          cmd: cd {{ .ITEM }} && task run
