name: PR
on:
  pull_request:
      branches:
        - 'main'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - uses: golangci/golangci-lint-action@v3
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - run: go test -v ./...
  example-directories:
    runs-on: ubuntu-latest
    outputs:
      directories: ${{ steps.set-directories.outputs.directories }}
      steps:
        - uses: actions/checkout@v2
        - id: set-directories
          run: echo "::set-output name=directories::$(ls examples -d | jq -R -s -c 'split("\n")[:-1]')"
  examples:
    runs-on: ubuntu-latest
    needs: example-directories
    strategy:
      matrix:
        manifest: ${{ fromJson(needs.example-directories.outputs.directories) }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.19
          cache-dependency-path: examples/${{ martix.manifest }}/go.sum
      - name: Install Dependencies
        working-directory: examples/${{ martix.manifest }}
        run: go get .
      - name: Build ${{ martix.manifest }}
        working-directory: examples/${{ martix.manifest }}
        run: go build .