name: Sync Dependencies
on:
  pull_request:
    branches:
      - 'main'
    types:
      - 'opened'
      - 'synchronize'
      - 'reopened'
jobs:
  sync-dependencies:
    if: startsWith(github.actor, 'dependabot')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.0
      - name: Sync all dependencies
        run: |
          find . -name 'go.mod' -execdir go mod tidy \;
      - name: Check for changes
        id: git_status
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "has_changes=true" >> $GITHUB_ENV
          else
            echo "has_changes=false" >> $GITHUB_ENV
          fi
      - name: Commit and push changes
        if: env.has_changes == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore(deps): sync updated dependencies [dependabot skip]"
          git push origin HEAD:${{ github.head_ref }}
      - name: No changes
        if: env.has_changes == 'false'
        run: |
          echo "No changes detected"
